idf_component_register(
    SRCS
        "main.c"
        "board.c"
        "colorcal.c"
        "pmic.cpp"
        "ui.c"
        "ui_render.c"
        "gfx.c"
        "light.c"
        "wifi_mgr.c"
        "http_api.c"
        "console_cmd.c"
        "lineedit.c"
        "audio.c"
        "settings.c"
        "uploader.c"
        "bridge.c"
        "imu.c"
        "camera.c"
        "ink.c"
        "png.c"
        "pics.c"
        "imgdec.c"
        "picview.c"
        "imgrot.c"
        "storage.c"
        "cam_ui.c"
        "fonts/font_face96.c"
        "fonts/font_face64.c"
        "fonts/font_face44.c"
        "fonts/font_face30.c"
        "fonts/font_face18.c"
        "fonts/font_face13.c"
        "fonts/font_text22.c"
        "fonts/font_small14.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        esp_lcd
        esp_lcd_st7796
        es8311
        XPowersLib
        driver
        esp_driver_i2s
        nvs_flash
        esp_wifi
        esp_netif
        lwip
        esp_event
        esp_http_server
        esp_http_client
        console
        esp_timer
        json
        esp32-camera
        fatfs
        esp_driver_sdmmc
        esp_driver_usb_serial_jtag
        sdmmc
        wear_levelling
        vfs
)
